### PR TITLE
Added the FB Spider Logo

### PR DESCRIPTION
**Pull request by yashrsharma44**
Added a logo for FB Spider. PR for the issue number #50

### CODE REVIEW

**Comment by Parth-Vader** [comment]
@yashrsharma44 I really like this :heart: 
But can the colors be improved? The yellow-black combination seems a little off. What do you think about the original F logo for Facebook, and half of your spider in the right side? :sweat_smile:

**Comment by yashrsharma44** [comment]
I have changed the Logo, please review.

**Comment by Parth-Vader** [comment]
The color combination is great, but I don't like this "spider" written. What I suggested was the original f logo of Facebook in the whole logo, plus half spider on the right side (projecting out). What do you think about this?

**Comment by yashrsharma44** [comment]
I am adding the Logo here itself, you can have a look into it - 
fbsp

**Comment by Parth-Vader** [comment]
@yashrsharma44 This looks cool! Can you add this?

**Comment by yashrsharma44** [comment]
Thanks, adding it.

**Comment by yashrsharma44** [comment]
Added the Logo(s), please review.

**Pull request merged**
