### PR TITLE
Added the Back to Top markdown

### PR DESCRIPTION
**Pull request by yashrsharma44**

### CODE REVIEW

**Comment by Parth-Vader** [comment]
Needed a GIF for your GUI program, as well as a logo (if you can make one!).
This PR is too insignificant.

**Comment by yashrsharma44** [comment]
Added the GIF. Wanted to add the GIF, but internet was not working, so sorry for the delay.

**Comment by Parth-Vader** [comment]
Cool! merging :smile:

**Comment by SubhrajitPrusty** [comment]
Can anyone reduce the file size of the GUI gif? It takes a lot of time to load.

**Pull request merged**
