### PR TITLE
Modified table

### PR DESCRIPTION
**Pull request by sarthakmadaan**

### CODE REVIEW

**Comment by Parth-Vader** [comment]
@sarthak5 Remove the conflicts manually.

**Comment by Parth-Vader** [comment]
@sarthak5 I dont see the name of the commentor/date etc.

**Comment by sarthakmadaan** [comment]
I think I accidentally made the change in last commit, will correct it.

**Comment by sarthakmadaan** [comment]
@Parth-Vader there shouldn't be any problems now.

**Comment by Parth-Vader** [comment]
@sarthak5 Nice work. :+1: Merging.

**Pull request merged**
