### PR TITLE
Added instructions for CLI

### PR DESCRIPTION
**Pull request by SubhrajitPrusty**

### CODE REVIEW

**Comment by SubhrajitPrusty** [comment]
fixes #55

**Comment by Parth-Vader** [comment]
@SubhrajitPrusty Great work, but can you add the contents of `CLI.md` in `README.md` itself? I don't think creating another file is required here.

**Comment by SubhrajitPrusty** [comment]
It can be done. But I think it makes the README quite bulky, with the already present instructions and gifs.

**Comment by Parth-Vader** [comment]
It's fine I guess if there's an index and 'back to top' options. See [this readme](https://github.com/athityakumar/colorls) for example.

**Comment by SubhrajitPrusty** [comment]
fixed.

**Comment by Parth-Vader** [comment]
@SubhrajitPrusty Great work! Thanks a lot. Merging!

**Pull request merged**
