### PR TITLE
modified table, added created time and name of commenter, removed unw…

### PR DESCRIPTION
**Pull request by sarthakmadaan**
…anted elements

### CODE REVIEW

**Comment by sarthakmadaan** [comment]
Addressed issue #6 and #4

**Comment by sarthakmadaan** [comment]
I have tried many different pages and it seems to be working fine. I don't get why it is failing checks.

**Comment by Parth-Vader** [comment]
Don't see the checks.
I haven't configured it properly.

**Comment by Parth-Vader** [comment]
It's working fine :+1:

**Comment by Parth-Vader** [comment]
@sarthak5 Send the PR to TableModified Branch.

**Comment by sarthakmadaan** [comment]
I have sent the PR to TableModified Branch and there are some conflicts. I am closing this PR.

**Pull request closed without merging**
